### ISSUE TITLE
please help me about hdmi output.

### ISSUE THREAD

**Issue by luceat-lux-vestra** [1999-born/Hackintosh-dell-7373#1]
Do you have 8250u with hd620 model?

I'm working on that but no luck.

HDMI output (had to patch whatevergreen)

How can I patch whatevergreen?

Thanks in advance.

**Comment by 1999-born** [comment]
I'm guessing you're using OpenCore, If so. then you need to edit the config.plist file.
![Screenshot 2021-05-07 at 2 45 32 PM](https://user-images.githubusercontent.com/83516047/117427671-e3d4ab80-af42-11eb-8ab0-48466c6cc157.png)


This is what my path looks like.
make sure you enable "enable-hdmi20"

**Comment by luceat-lux-vestra** [comment]
I tried but it's not working sadly.

Do you mind make keep up to date this repository?

I'm just start using my hackintosh with yours.
It seems works fine.

Thanks.

**Comment by 1999-born** [comment]
This might be different for your GPU as it might be on a different PCI port, if you don't have the exact laptop you need to change a few thing here and there

Check this out. this is for UHD620.

https://www.reddit.com/r/hackintosh/comments/hu46xm/fix_hdmi_port_and_possibly_others_not_working_on/

![Screenshot 2021-05-07 at 5 26 29 PM](https://user-images.githubusercontent.com/83516047/117446227-649ea200-af59-11eb-9ad9-91f4dea9c567.png)

pci(0x2,0x0) to whatever your pci port is (IGPU@2 in my Screenshot)

this app is IORegistryExplorer
